# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170704_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('sub1', models.CommaSeparatedIntegerField(max_length=100)),
                ('sub2', models.CommaSeparatedIntegerField(max_length=100)),
            ],
        ),
    ]
