# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170705_0540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studentid',
            new_name='parentid',
        ),
        migrations.AddField(
            model_name='profile',
            name='childid',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
