# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170705_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='sub1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sub2',
        ),
    ]
