# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-17 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sub3_sub4_sub5'),
    ]

    operations = [
        migrations.CreateModel(
            name='tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('compname', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=20)),
                ('studenti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
        migrations.RemoveField(
            model_name='sub1',
            name='studenti',
        ),
        migrations.RemoveField(
            model_name='sub2',
            name='studenti',
        ),
        migrations.RemoveField(
            model_name='sub3',
            name='studenti',
        ),
        migrations.RemoveField(
            model_name='sub4',
            name='studenti',
        ),
        migrations.RemoveField(
            model_name='sub5',
            name='studenti',
        ),
        migrations.DeleteModel(
            name='sub1',
        ),
        migrations.DeleteModel(
            name='sub2',
        ),
        migrations.DeleteModel(
            name='sub3',
        ),
        migrations.DeleteModel(
            name='sub4',
        ),
        migrations.DeleteModel(
            name='sub5',
        ),
    ]
