# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-17 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180117_0617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tech',
            old_name='compname',
            new_name='name',
        ),
    ]
