# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-18 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180117_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech',
            name='user_name',
        ),
        migrations.AddField(
            model_name='tech',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
            preserve_default=False,
        ),
    ]
